import { Button } from "@/components/ui/button";
import { Download, FileSpreadsheet, FileText } from "lucide-react";
import { PriceVolumeData } from "@/types/priceVolume";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { toast } from "sonner";

interface ExportButtonProps {
  data: PriceVolumeData;
}

function formatCurrency(value: number): string {
  if (value >= 1000000) {
    return `£${(value / 1000000).toFixed(1)}M`;
  }
  return `£${(value / 1000).toFixed(0)}K`;
}

export function ExportButton({ data }: ExportButtonProps) {
  const generateCSV = () => {
    const headers = [
      "SKU ID",
      "Name",
      "Category",
      "Geography",
      "Current Revenue",
      "Previous Revenue",
      "Change %",
      "Price Change %",
      "Volume Change %",
      "Mix Change %",
    ];

    const rows = data.skus.map((sku) => {
      const changePercent = ((sku.currentRevenue - sku.previousRevenue) / sku.previousRevenue) * 100;
      return [
        sku.id,
        sku.name,
        sku.category,
        sku.geography,
        sku.currentRevenue,
        sku.previousRevenue,
        changePercent.toFixed(1),
        sku.priceVolumeMix.priceChange.toFixed(1),
        sku.priceVolumeMix.volumeChange.toFixed(1),
        sku.priceVolumeMix.mixChange.toFixed(1),
      ];
    });

    const csvContent = [headers, ...rows]
      .map((row) => row.map((cell) => `"${cell}"`).join(","))
      .join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `price-volume-analysis-${data.summary.period}.csv`;
    link.click();
    URL.revokeObjectURL(link.href);
    
    toast.success("Export complete", {
      description: "CSV file downloaded successfully",
    });
  };

  const generatePDFContent = () => {
    // Generate a text-based report that can be saved
    const report = `
PRICE VOLUME ANALYSIS REPORT
============================
Period: ${data.summary.period} vs ${data.summary.previousPeriod}
Generated: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
-----------------
Total Current Revenue: ${formatCurrency(data.summary.totalCurrentRevenue)}
Total Previous Revenue: ${formatCurrency(data.summary.totalPreviousRevenue)}
Total Change: ${formatCurrency(data.summary.totalChange)} (${data.summary.totalChangePercent > 0 ? '+' : ''}${data.summary.totalChangePercent.toFixed(1)}%)

PRICE/VOLUME/MIX BREAKDOWN
--------------------------
Price Impact: ${data.summary.priceVolumeMix.priceChange > 0 ? '+' : ''}${data.summary.priceVolumeMix.priceChange.toFixed(1)}%
Volume Impact: ${data.summary.priceVolumeMix.volumeChange > 0 ? '+' : ''}${data.summary.priceVolumeMix.volumeChange.toFixed(1)}%
Mix Impact: ${data.summary.priceVolumeMix.mixChange > 0 ? '+' : ''}${data.summary.priceVolumeMix.mixChange.toFixed(1)}%

KEY INSIGHTS
------------
${data.keyInsights.map((insight, i) => `${i + 1}. ${insight}`).join('\n')}

GEOGRAPHY BREAKDOWN
-------------------
${data.geographies.map(geo => 
  `${geo.name}: ${formatCurrency(geo.currentRevenue)} (${geo.priceVolumeMix.totalChange > 0 ? '+' : ''}${geo.priceVolumeMix.totalChange.toFixed(1)}%)`
).join('\n')}

PRODUCT GROUP BREAKDOWN
-----------------------
${data.productGroups.map(pg => 
  `${pg.name}: ${formatCurrency(pg.currentRevenue)} (${pg.priceVolumeMix.totalChange > 0 ? '+' : ''}${pg.priceVolumeMix.totalChange.toFixed(1)}%)`
).join('\n')}

TOP SKUs BY REVENUE
-------------------
${data.skus.slice(0, 10).map((sku, i) => {
  const changePercent = ((sku.currentRevenue - sku.previousRevenue) / sku.previousRevenue) * 100;
  return `${i + 1}. ${sku.name} (${sku.id}): ${formatCurrency(sku.currentRevenue)} (${changePercent > 0 ? '+' : ''}${changePercent.toFixed(1)}%)`;
}).join('\n')}

---
Report generated by Price Volume Agent
    `.trim();

    const blob = new Blob([report], { type: "text/plain;charset=utf-8;" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `price-volume-report-${data.summary.period}.txt`;
    link.click();
    URL.revokeObjectURL(link.href);
    
    toast.success("Export complete", {
      description: "Report downloaded successfully",
    });
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Download className="h-4 w-4" />
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-48">
        <DropdownMenuItem onClick={generateCSV} className="gap-2 cursor-pointer">
          <FileSpreadsheet className="h-4 w-4 text-emerald-600" />
          <div>
            <p className="font-medium">Export as CSV</p>
            <p className="text-xs text-muted-foreground">SKU-level data</p>
          </div>
        </DropdownMenuItem>
        <DropdownMenuItem onClick={generatePDFContent} className="gap-2 cursor-pointer">
          <FileText className="h-4 w-4 text-blue-600" />
          <div>
            <p className="font-medium">Export Report</p>
            <p className="text-xs text-muted-foreground">Full analysis</p>
          </div>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
